### ISSUE TITLE
Element add/removeEventListener using specifies old API only

### ISSUE THREAD

**Issue by nhardy** [microsoft/TypeScript-DOM-lib-generator#273] opened 2017-07-04 07:04 UTC
It looks like `Element` and all types that inherit from it specify the old `addEventListener`/`removeEventListener` APIs with `useCapture?: boolean` instead of the newer `options?: boolean | AddEventListenerOptions`/`options?: boolean | EventListenerOptions` that does appear on `EventTarget`.

**Comment by saschanaz** [comment] 2021-09-17 12:25
Dupe of #174 which has been fixed

@github-actions close

**Closed** 2021-09-17 12:26 UTC
